[package]
name = "zescrow_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "2.1.0", default-features = false, features = ['std'] }
zescrow-core = { path = "../../core" }
