[workspace]
members = ["client", "core", "agent/solana/escrow/programs/escrow"]

resolver = "2"

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
